server:
    port: 8090
spring:
    application:
        name: spring-cloud-gateway
    cloud:
        gateway:
            enabled: true
            discovery:
                locator:
                    lower-case-service-id: true
            routes:
                # Add your routes here.
                -   id: aliyun_route
                    uri: https://www.aliyun.com/
                    predicates:
                        - Path=/product/**
                -   id: httpbin_route
                    uri: https://httpbin.org
                    predicates:
                        - Path=/httpbin/**
                    filters:
                        - RewritePath=/httpbin/(?<segment>.*), /$\{segment}
        sentinel:
            transport:
                port: 48719
                dashboard: localhost:8080